### ISSUE TITLE
Build failed

### ISSUE THREAD

**Issue by azureplus** [karelrooted/libmpv#1]
Build failed
-> missing file: '/Vendor/smbclient/bin/default/third_party/heimdal/lib/asn1/asn1_kx509_asn1.c'

Can you provide:
/usr/local/bin/asn1_compile
/usr/local/bin/compile_et

**Comment by karelrooted** [comment]
first compile for macOS, and then script will copy the generated  asn1_compile &&  compile_et to /usr/local/bin

if compile for other platform first , the script will fail (if use all default setting, macOS will be the first platform to build) (will add helpful message to remind user to build macOS first at the next release version)

smbclient is a WIP (have to figure out a way to generated a combined static lib or dynamic lib), currently in the process of  changing samba version to exactly the same as xbmc (4.15.13) , and use xbmc's samba [patch](https://github.com/xbmc/xbmc/tree/8d852242b8fed6fc99132c5428e1c703970f7201/tools/depends/target/samba-gplv3) to generate static lib

this is the asn1_compile && compile_et from my local Mac (x86_64) [samba_tool.zip](https://github.com/karelrooted/libmpv/files/13706852/samba_tool.zip)

**Comment by azureplus** [comment]
Reason: tried: '/usr/lib/system/introspection/libsmbclient.inst.dylib' (no such file, not in dyld cache),

**Comment by karelrooted** [comment]
the Libsmbclient.xcframework currently generated by the swift script does not work (is samba's default multi dylib structure),  only copy one lib in the framework will not work

please check out the latest git (commit is being rebased to one commit , please recheckout), and use the new shell building system, but currently only macOS  x86_64 machine can generate a combined macOS-x86_64 libsmbclient.a static lib (other platform is still WIP) , and macOS static lib is not tested (last time I briefly tested it , some library symbol is still missing, samba really make it difficult to generate a static lib...)

build:   
``` bash
./build.sh -p macos -a x86_64 -l "readline gmp nettle gnutls smbclient"
```
xcframework:   
``` bash
 ./xcframework.sh  -l "readline gmp nettle gnutls smbclient"
```

**Comment by azureplus** [comment]
OK，thanks， Continue to use the previous smbv2.
